<?php

use Drupal\media\IFrameMarkup;

function ddo_axeptio_preprocess_media_oembed_iframe(array &$variables) {

  // Gestion des cookies Axeptio : modification du code HTML de l'iframe video pour obtenir le consentement contextuel
  $axeptio_iframe_markup = str_replace(
    'src',
    'data-requires-vendor-consent="' . ucfirst(strtolower($variables['resource']->getProvider()->getName())) . '" data-src',
    (string) $variables['media']
  );
  $variables['media'] = IFrameMarkup::create($axeptio_iframe_markup);
}
